---
name: Pod-Tidy
version: 0.03
author: ~
abstract: ~
license: gpl
requires:
  File::Copy: 0
  IO::String: 0
  Pod::Find: 0
  Pod::Simple: 0
  Pod::Wrap: 0
  Text::Wrap: 0
build_requires:
  Test::Cmd: 0
  Test::Pod: 0.95
provides:
  Pod::Tidy:
    file: lib/Pod/Tidy.pm
    version: 0.03
  Pod::Wrap::Pretty:
    file: lib/Pod/Wrap/Pretty.pm
    version: 0.01
generated_by: Module::Build version 0.25
