---
name: Pod-Tidy
version: 0.08
author: ~
abstract: ~
license: perl
requires:
  Encode: 0
  Encode::Newlines: 0.03
  File::Copy: 0
  IO::String: 0
  Pod::Find: 0
  Pod::Simple: 0
  Pod::Wrap: 0
  Test::Cmd: 1.05
  Text::Glob: 0.06
  Text::Wrap: 0
recommends:
  Test::Distribution: 1.22
provides:
  Pod::Tidy:
    file: lib/Pod/Tidy.pm
    version: 0.08
  Pod::Wrap::Pretty:
    file: lib/Pod/Wrap/Pretty.pm
    version: 0.02
generated_by: Module::Build version 0.25
